version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:current
    resource_class: theqrl/qrysm-builder
    steps:
      - run: echo "Hi I'm on a Container Runner!"
      - run: sudo apt-get install dnsutils -y
      - run: dig +short myip.opendns.com @resolver1.opendns.com
workflows:
  build-workflow:
    jobs:
      - build
